Mwl 14 deploy first working version to heroku
VladimirKabar/P6 pull request #15
Opened 2016-10-27 09:42 UTC by VladimirKabar

working

2016-10-27 10:16 UTC, maciej-lorens requested changes

2016-10-27 10:16 UTC, mcksnk commented on config/database.yml
> +  database: project_development
this mean that I need the same databse name, change it to <%= ENV["WIZZART_DATABABASE %> and set env variable on your pc

2016-10-27 10:16 UTC, mcksnk commented on config/database.yml
> +  username: vladimir
this mean that I need the same username, change it to <%= ENV["WIZZART_USERNAME %> and set env variable on your pc

2016-10-27 10:16 UTC, mcksnk commented on Gemfile
> -gem 'jquery-rails'
do we really have to remote it?

2016-10-27 12:55 UTC, maciej-lorens requested changes

2016-10-27 12:55 UTC, mcksnk commented on db/seeds.rb
> -end
instead of removing it, maybe lets upload image from http://placehold.it/

2016-10-28 07:59 UTC, mcksnk commented on db/seeds.rb
> +[p1, p2, p3, p4,p5,p6,p7,p8].each do |project|
for future, you can use here:
> Project.all.each.do |project|

2016-10-28 07:59 UTC, maciej-lorens approved these changes

2016-10-28 09:03 UTC, merged