Mwl 27 add contact form
VladimirKabar/P6 pull request #23
Opened 2016-11-20 19:51 UTC by VladimirKabar

2016-11-21 09:18 UTC, maciej-lorens requested changes

2016-11-21 09:18 UTC, mcksnk commented on config/routes.rb
> +  post 'kontakt' =>  'static_pages#create'
keep english names

2016-11-21 09:18 UTC, mcksnk commented on config/routes.rb
> +  post 'kontakt' =>  'static_pages#create'
static_pages#new and static_pages#create doesnt suggest it's related contact form

2016-11-21 09:18 UTC, mcksnk commented on db/schema.rb
> +  end
do we need this model? what does it keep?

2016-11-21 09:18 UTC, mcksnk commented on app/mailers/application_mailer.rb
> +  default from: 'noreply@wizzart.com'
put it to ENV variable so it can be changed without deploy

2016-11-21 09:18 UTC, mcksnk commented on app/mailers/mailer_notifier_mailer.rb
> +    mail to: "masterrascal@gmail.com",
put it to ENV variable so it can be changed without deploy

2016-11-21 09:18 UTC, mcksnk commented on app/controllers/static_pages_controller.rb
> +      redirect_to kontakt_path, notice: "Twoja wiadomość została wysłana"
keep english names

2016-11-21 09:18 UTC, mcksnk commented on app/controllers/static_pages_controller.rb
> +      MailerNotifierMailer.mail_to_me(@message).deliver
1) remove `kontakt` and `new` actions
2) remove Message model
3) change this line to MailerNotifierMailer.mail_to_me(params[:email], params[:name], params[:content]).deliver
4) change mail form url to this actions with :email, :name and :content parameters
5) you can change this action name to contact, as `create` in static_pages controller is misleading

2016-11-21 22:23 UTC, maciej-lorens approved these changes

2016-11-21 22:23 UTC, mcksnk commented on app/controllers/static_pages_controller.rb
> +
You can remove it

2016-11-21 22:23 UTC, mcksnk commented on app/controllers/static_pages_controller.rb
> +  def contact
You can remove it

2016-11-21 22:23 UTC, mcksnk commented on config/routes.rb
> +  match '/contact' , to: 'static_pages#mail', via: 'post'
Choose one route

2016-11-22 20:24 UTC, VladimirKabar commented on config/routes.rb
> +  match '/contact' , to: 'static_pages#mail', via: 'post'
but why? if i delete route 'post' for_tag won't pass (there is only definded get request)

2016-11-22 21:58 UTC, mcksnk commented on config/routes.rb
> +  match '/contact' , to: 'static_pages#mail', via: 'post'
Ok, so change it to match /mail instead od match /contact

2016-11-24 08:53 UTC, maciej-lorens approved these changes

2016-11-24 18:19 UTC, merged