poprawki tu i owdzie
VladimirKabar/P6 pull request #9
Opened 2016-10-20 22:34 UTC by VladimirKabar

2016-10-21 09:37 UTC, maciej-lorens requested changes

2016-10-21 09:37 UTC, mcksnk commented on app/views/static_pages/home/_recent_products.html.erb
> +                        <p><%= p.description %></p>
move this tag inside `entry-content woocommerce` div, right after `spa-wrap-line` div

2016-10-21 09:37 UTC, mcksnk commented on app/views/static_pages/home/_recent_products.html.erb
> +                        </div>
move `entry-content woocommerce` div outside `entry-thumb spa-hover-effect-2` div. `entry-content woocommerce` div should be on the same level as `entry-thumb spa-hover-effect-2` div, not inside it.

2016-10-21 09:37 UTC, mcksnk commented on db/seeds.rb
> +end
think about refactoring it, maybe there is better way of creating 4 resources for each project

2016-10-21 16:01 UTC, VladimirKabar commented on db/seeds.rb
> +end
done

2016-10-21 16:03 UTC, VladimirKabar commented on app/views/static_pages/home/_recent_products.html.erb
> +                        <p><%= p.description %></p>
done

2016-10-21 16:03 UTC, VladimirKabar commented on app/views/static_pages/home/_recent_products.html.erb
> +                        </div>
done

2016-10-22 10:28 UTC, maciej-lorens approved these changes

2016-10-23 16:55 UTC, mcksnk commented
approved

2016-10-23 17:12 UTC, merged